kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: blockallfrontendpolicy
  namespace: blockap
spec:
  podSelector:
    matchLabels:
      group: blockapplication          
  ingress: []