kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: blockallbackendpolicy
  namespace: blockapp2
spec:
  podSelector:
    matchLabels:
      group: blockapplication          
  ingress: []